[tool.poetry]
name = "recommendations"
version = "0.1.0"
description = ""
authors = ["Nicolò Boschi <boschi1997@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ragstack-ai = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
